In [22]:
# 2 dimensional gf table
from numpy import zeros, set_printoptions
prec = 18 #relates to dim
set_printoptions(suppress=True, linewidth=1500)
R.<x,y> = PowerSeriesRing(QQ, default_prec=prec); R

f = (1-x-y)/((1-x-y)**2 -x*y)
g = (1)/((1-x-y)**2 -x*y)
cc = (1 -x*y)*(1+f*(x+y))

c_0 = y**2*x**3/((1-y)*(1-x)**2) + x**2*y**3/((1-x)*(1-y)**2) # done
c_1 = 2*x*y/((1-x)*(1-y))*(f*(x/(1-x)+y/(1-y))+g*(x*(y**2)/(1-x)+(x**2)*y/(1-y))) - (2*x**2*y/((1-x)**3*(1-y))+2*y**2*x/((1-y)**3*(1-x))) # done
c_2 = (1/((1-x)*(1-y)) -1)*(cc -(x/(1-x)) -(y/(1-y))- 2) + x/(1-x) + y/(1-y) +(x*y)

c_3=(x/(1-x)**2)*(y/(1-y)**2) + y**2*(x**4/((1-x)**3*(1-y))) + x**2*(y**4/((1-y)**3*(1-x))) - x*y/((1-x)**2) -x*y/((1-y)**2) + x*y # done
c = c_0 + c_1 + c_2 + c_3 - x*y - x**2*y/((1-x)**4) + y/(1-x) - x*y**2/((1-y)**4) + x/(1-y) -x*y + x**2/(1-x) + y**2/(1-y)

i_0 = 2*x*x*y*y/(((1-x)**2)*((1-y)**2)) + x*x*x*y*y/(((1-x)**3)*((1-y)**2)) + x*x*y*y*y/(((1-x)**2)*((1-y)**3)) # done
i_1 = c_1*(-1+(1/((1-x)*(1-y)))) # done
i_11 = (2*x**2*y**3)/(((1-x)**2)*((1-y)**3)) + (2*x**3*y**2)/(((1-x)**3)*((1-y)**2)) + (2*x**2*y**4)/(((1-x)**2)*((1-y)**4)) + (2*x**4*y**2)/(((1-x)**4)*((1-y)**2)) # done
r_1 = 2*x**5*y**2/(((1-x)**4)*(1-y)) + 2*y**5*x**2/(((1-y)**4)*(1-x))
i_2 = c_2*(-1+(1/((1-x)*(1-y)))) - x**2*y*(x/((1-x)**4) - 1/((1-x)) + 1)/(1-x) - x*y**2*(y/((1-y)**4) - 1/((1-y)) + 1)/(1-y) - 2*x*x*y*y/(((1-x)**2)*((1-y)**2)) + 2/((1-x)*(1-y)) - 2/(1-x) - 2/(1-y) - 2*x*y/(1-x) - 2*x*y/(1-y) + 2*x*y +2
i_3 = (4*f*x**2*y**3)/(((1-x)**2)*((1-y)**4)) +(4*f*x**3*y**2)/(((1-x)**4)*((1-y)**2)) # done
r_3 = 4*x**3*y**2/(((1-x)**4)*((1-y)**2)) + 4*x**2*y**3/(((1-x)**2)*((1-y)**4)) # done
i_4 = 4*g*x**3*y**3/(((1-x)**3)*((1-y)**3)) # done
i_5 = x*y/(((1-x)**2)*((1-y)**2)) - 4*x**2*y**2/(((1-x))*((1-y))) -x*y/((1-x)**2)-x*y/((1-y)**2)+x*y # done
i = 2*i_0 + 4*i_1 + 4*i_11 + r_1 + 2*i_2 + 2*i_3 - r_3 + 4*i_4 + i_5

t_r = 6*x**2*y**2/(((1-x)**2)*(1-y)) + 6*x**2*y**2/(((1-y)**2)*(1-x)) # something funky going on here

t = 2*cc + 4*c + i - t_r -2/(1-x) -2/(1-y) + 2 -2*x*y/((1-x)**3) -2*x*y/((1-y)**3) +x*y - 4*y/(1-y) - 4*x/(1-x) + y*(x+3*x**2-x**3-x**4)/((1-x)**5) + x*(y+3*y**2-y**3-y**4)/((1-y)**5)

dim = prec//2
gftable=zeros((dim,dim))
coefs = (2*cc + 4*c - t_r).coefficients()
coefs = cc.coefficients()
coefs = t.coefficients()

for n in range(dim):
    for m in range(dim):
        try:
            gftable[n][m] = coefs[x^n*y^m]
        except KeyError:
            pass

print(gftable)

[[       0.        0.        0.        0.        0.        0.        0.        0.        0.]
 [       0.        1.        8.       29.       74.      155.      286.      483.      764.]
 [       0.        8.       68.      266.      752.     1758.     3620.     6802.    11922.]
 [       0.       29.      266.     1113.     3428.     8815.    20046.    41633.    80578.]
 [       0.       74.      752.     3428.    11616.    33036.    83206.   191218.   408600.]
 [       0.      155.     1758.     8815.    33036.   104097.   290164.   736027.  1730042.]
 [       0.      286.     3620.    20046.    83206.   290164.   892516.  2488684.  6404282.]
 [       0.      483.     6802.    41633.   191218.   736027.  2488684.  7594389. 21295332.]
 [       0.      764.    11922.    80578.   408600.  1730042.  6404282. 21295332. 64785360.]]


In [28]:
x,y = var('x,y')

f = (1-x-y)/((1-x-y)**2 -x*y)
g = (1)/((1-x-y)**2 -x*y)

cc = (1 -x*y)*(1+f*(x+y))
cc_main = (1 -x*y)*((1-x-y)*(x+y))
cc_side = (1 -x*y)
assert cc_main*g + cc_side == cc

c_0 = y**2*x**3/((1-y)*(1-x)**2) + x**2*y**3/((1-x)*(1-y)**2)

c_1 = 2*x*y/((1-x)*(1-y))*(f*(x/(1-x)+y/(1-y))+g*(x*(y**2)/(1-x)+(x**2)*y/(1-y))) - (2*x**2*y/((1-x)**3*(1-y))+2*y**2*x/((1-y)**3*(1-x)))
c_1_main = (2*x*y/((1-x)*(1-y)))*((1-x-y)*(x/(1-x)+y/(1-y))+(x*(y**2)/(1-x)+(x**2)*y/(1-y)))
c_1_side = - (2*x**2*y/((1-x)**3*(1-y))+2*y**2*x/((1-y)**3*(1-x)))
assert c_1_main*g + c_1_side == c_1

c_2 = (1/((1-x)*(1-y)) -1)*(cc -(x/(1-x)) -(y/(1-y))- 2) + x/(1-x) + y/(1-y) +(x*y)
c_2_main = (1/((1-x)*(1-y)) -1)*((1 -x*y)*((x+y))*(1-x-y))
c_2_side = (1/((1-x)*(1-y)) -1)*((1 -x*y) - (x/(1-x)) -(y/(1-y))- 2) + x/(1-x) + y/(1-y) +(x*y)
assert c_2_main*g + c_2_side == c_2

c_3=(x/(1-x)**2)*(y/(1-y)**2) + y**2*(x**4/((1-x)**3*(1-y))) + x**2*(y**4/((1-y)**3*(1-x))) - x*y/((1-x)**2) -x*y/((1-y)**2) + x*y

c = c_0 + c_1 + c_2 + c_3 - x*y - x**2*y/((1-x)**4) + y/(1-x) - x*y**2/((1-y)**4) + x/(1-y) -x*y + x**2/(1-x) + y**2/(1-y)
c_main = c_1_main + c_2_main
c_side = c_0 + c_1_side + c_2_side + c_3  - x*y - x**2*y/((1-x)**4) + y/(1-x) - x*y**2/((1-y)**4) + x/(1-y) -x*y + x**2/(1-x) + y**2/(1-y)
assert c_main*g + c_side == c

i_0 = 2*x*x*y*y/(((1-x)**2)*((1-y)**2)) + x*x*x*y*y/(((1-x)**3)*((1-y)**2)) + x*x*y*y*y/(((1-x)**2)*((1-y)**3))
i_1 = c_1*(-1+(1/((1-x)*(1-y))))
i_1_main = c_1_main*(-1+(1/((1-x)*(1-y))))
i_1_side = c_1_side*(-1+(1/((1-x)*(1-y))))
assert i_1_main*g + i_1_side == i_1

i_11 = (2*x**2*y**3)/(((1-x)**2)*((1-y)**3)) + (2*x**3*y**2)/(((1-x)**3)*((1-y)**2)) + (2*x**2*y**4)/(((1-x)**2)*((1-y)**4)) + (2*x**4*y**2)/(((1-x)**4)*((1-y)**2))
r_1 = 2*x**5*y**2/(((1-x)**4)*(1-y)) + 2*y**5*x**2/(((1-y)**4)*(1-x))
i_2 = c_2*(-1+(1/((1-x)*(1-y)))) - x**2*y*(x/((1-x)**4) - 1/((1-x)) + 1)/(1-x) - x*y**2*(y/((1-y)**4) - 1/((1-y)) + 1)/(1-y) - 2*x*x*y*y/(((1-x)**2)*((1-y)**2)) + 2/((1-x)*(1-y)) - 2/(1-x) - 2/(1-y) - 2*x*y/(1-x) - 2*x*y/(1-y) + 2*x*y +2
i_2_main = c_2_main*(-1+(1/((1-x)*(1-y))))
i_2_side = c_2_side*(-1+(1/((1-x)*(1-y)))) - x**2*y*(x/((1-x)**4) - 1/((1-x)) + 1)/(1-x) - x*y**2*(y/((1-y)**4) - 1/((1-y)) + 1)/(1-y) - 2*x*x*y*y/(((1-x)**2)*((1-y)**2)) + 2/((1-x)*(1-y)) - 2/(1-x) - 2/(1-y) - 2*x*y/(1-x) - 2*x*y/(1-y) + 2*x*y +2
assert i_2_main*g + i_2_side == i_2

i_3 = (4*f*x**2*y**3)/(((1-x)**2)*((1-y)**4)) +(4*f*x**3*y**2)/(((1-x)**4)*((1-y)**2))
i_3_main = (4*(1-x-y)*x**2*y**3)/(((1-x)**2)*((1-y)**4)) +(4*(1-x-y)*x**3*y**2)/(((1-x)**4)*((1-y)**2))

r_3 = 4*x**3*y**2/(((1-x)**4)*((1-y)**2)) + 4*x**2*y**3/(((1-x)**2)*((1-y)**4))
i_4 = 4*g*x**3*y**3/(((1-x)**3)*((1-y)**3))
i_4_main = 4*x**3*y**3/(((1-x)**3)*((1-y)**3))

i_5 = x*y/(((1-x)**2)*((1-y)**2)) - 4*x**2*y**2/(((1-x))*((1-y))) -x*y/((1-x)**2)-x*y/((1-y)**2)+x*y
i = 2*i_0 + 4*i_1 + 4*i_11 + r_1 + 2*i_2 + 2*i_3 - r_3 + 4*i_4 + i_5

i_main = 4*i_1_main + 2*i_2_main + 2*i_3_main + 4*i_4_main
i_side = 2*i_0 + 4*i_1_side + 4*i_11 + r_1 + 2*i_2_side - r_3 + i_5
    
assert i_main*g + i_side == i

t_r = 6*x**2*y**2/(((1-x)**2)*(1-y)) + 6*x**2*y**2/(((1-y)**2)*(1-x))
t = 2*cc + 4*c + i - t_r -2/(1-x) -2/(1-y) + 2 -2*x*y/((1-x)**3) -2*x*y/((1-y)**3) +x*y - 4*y/(1-y) - 4*x/(1-x) + y*(x+3*x**2-x**3-x**4)/((1-x)**5) + x*(y+3*y**2-y**3-y**4)/((1-y)**5)

t_main = 2*cc_main + 4*c_main + i_main

t_side = 2*cc_side + 4*c_side + i_side - t_r -2/(1-x) -2/(1-y) + 2 -2*x*y/((1-x)**3) -2*x*y/((1-y)**3) +x*y - 4*y/(1-y) - 4*x/(1-x) + y*(x+3*x**2-x**3-x**4)/((1-x)**5) + x*(y+3*y**2-y**3-y**4)/((1-y)**5)

assert t_main*g + t_side == t
print(latex(factor(t_main.numerator())))
print(latex(factor(t_main.denominator())))
print(latex(factor(t_side.numerator())))
print(latex(factor(t_side.denominator())))



# print(latex(factor(t.numerator())))
# print(latex(factor(t.denominator())))


-14 \, x^{5} y^{3} + 4 \, x^{4} y^{4} - 14 \, x^{3} y^{5} + 4 \, x^{5} y^{2} + 42 \, x^{4} y^{3} + 42 \, x^{3} y^{4} + 4 \, x^{2} y^{5} + 2 \, x^{5} y - 34 \, x^{4} y^{2} - 88 \, x^{3} y^{3} - 34 \, x^{2} y^{4} + 2 \, x y^{5} + 6 \, x^{4} y + 72 \, x^{3} y^{2} + 72 \, x^{2} y^{3} + 6 \, x y^{4} - 2 \, x^{4} - 26 \, x^{3} y - 64 \, x^{2} y^{2} - 26 \, x y^{3} - 2 \, y^{4} + 6 \, x^{3} + 28 \, x^{2} y + 28 \, x y^{2} + 6 \, y^{3} - 6 \, x^{2} - 12 \, x y - 6 \, y^{2} + 2 \, x + 2 \, y
{\left(x - 1\right)}^{4} {\left(y - 1\right)}^{4}
2 \, x^{4} y^{2} + x^{3} y^{3} + 2 \, x^{2} y^{4} - 10 \, x^{3} y^{2} - 10 \, x^{2} y^{3} - x^{3} y + 28 \, x^{2} y^{2} - x y^{3} - 8 \, x^{2} y - 8 \, x y^{2} + 2 \, x^{2} + 5 \, x y + 2 \, y^{2} - 2 \, x - 2 \, y
{\left(x - 1\right)}^{4} {\left(y - 1\right)}^{4}


Numerator of original:
${\left(2 \, x^{5} y - 11 \, x^{4} y^{2} + 9 \, x^{3} y^{3} - 11 \, x^{2} y^{4} + 2 \, x y^{5} - 10 \, x^{4} y + 16 \, x^{3} y^{2} + 16 \, x^{2} y^{3} - 10 \, x y^{4} + x^{4} + 15 \, x^{3} y - 21 \, x^{2} y^{2} + 15 \, x y^{3} + y^{4} - 8 \, x^{2} y - 8 \, x y^{2} - 4 \, x^{2} + 5 \, x y - 4 \, y^{2} + 2 \, x + 2 \, y + 1\right)} x y$

Denominator of original:
${\left(x^{2} + x y + y^{2} - 2 \, x - 2 \, y + 1\right)} {\left(x - 1\right)}^{4} {\left(y - 1\right)}^{4}$

t_main numerator:
$-14 \, x^{5} y^{3} + 4 \, x^{4} y^{4} - 14 \, x^{3} y^{5} + 4 \, x^{5} y^{2} + 42 \, x^{4} y^{3} + 42 \, x^{3} y^{4} + 4 \, x^{2} y^{5} + 2 \, x^{5} y - 34 \, x^{4} y^{2} - 88 \, x^{3} y^{3} - 34 \, x^{2} y^{4} + 2 \, x y^{5} + 6 \, x^{4} y + 72 \, x^{3} y^{2} + 72 \, x^{2} y^{3} + 6 \, x y^{4} - 2 \, x^{4} - 26 \, x^{3} y - 64 \, x^{2} y^{2} - 26 \, x y^{3} - 2 \, y^{4} + 6 \, x^{3} + 28 \, x^{2} y + 28 \, x y^{2} + 6 \, y^{3} - 6 \, x^{2} - 12 \, x y - 6 \, y^{2} + 2 \, x + 2 \, y$

t_main denominator:
${\left(x - 1\right)}^{4} {\left(y - 1\right)}^{4}$

t_side numerator:
$2 \, x^{4} y^{2} + x^{3} y^{3} + 2 \, x^{2} y^{4} - 10 \, x^{3} y^{2} - 10 \, x^{2} y^{3} - x^{3} y + 28 \, x^{2} y^{2} - x y^{3} - 8 \, x^{2} y - 8 \, x y^{2} + 2 \, x^{2} + 5 \, x y + 2 \, y^{2} - 2 \, x - 2 \, y$

t_side denominator:
${\left(x - 1\right)}^{4} {\left(y - 1\right)}^{4}$

In [36]:
# test for simple functions
x,y,z,r = var('x,y,z,r')

test = t
test2 = test.subs(x==r*z)
test3 = test2.subs(y==r/z)

final = test3/z

res_sum = 0
for root in final.denominator().roots(z):
    if root[0].subs(r==0.00001) < 1: # worst limit check ever written i should be smited for this line of code
        print(f'mult {root[1]} root value: {root[0]}')
        if root[1] == 1:
            res_term = (final.numerator()/((final.denominator()).derivative(z))).subs(z==root[0]) # residue calculation for men
        elif root[1] > 1:
            temp_expr = ((z-root[0])**root[1]) * final
            for _ in range(root[1]-1):
                temp_expr = temp_expr.derivative(z)
            # temp_expr = temp_expr.subs(z==root[0])
            temp_expr = limit(temp_expr, z=root[0])

            res_term = temp_expr/factorial(root[1]-1)
        # print(res_term.simplify_full())
        res_sum += res_term
        print(res_sum.subs(r==x).simplify_full())        
print(res_sum.subs(r==x**(1/2)).simplify_full())



mult 1 root value: -1/2*(r + sqrt(-3*r^2 - 2*r + 1) - 1)/r
(9*x^9 + 33*x^8 - 107*x^7 + 9*x^6 + 136*x^5 - 74*x^4 - 23*x^3 + 17*x^2 - (9*x^8 - 30*x^7 - 5*x^6 + 80*x^5 - 58*x^4 - 10*x^3 + 15*x^2 - 1)*sqrt(-3*x^2 - 2*x + 1) + x - 1)/(3*x^11 + 5*x^10 - 17*x^9 - 43*x^8 - 14*x^7 + 28*x^6 + 15*x^5 - 7*x^4 - 3*x^3 + x^2 + (x^10 + 8*x^9 + 13*x^8 - 4*x^7 - 20*x^6 - 6*x^5 + 7*x^4 + 2*x^3 - x^2)*sqrt(-3*x^2 - 2*x + 1))
mult 1 root value: 1/2*(r - sqrt(-3*r^2 + 2*r + 1) + 1)/r
2*(27*x^18 - 639*x^16 + 3475*x^14 - 915*x^12 - 6430*x^10 + 5504*x^8 - 1813*x^6 + 305*x^4 - 27*x^2 + (9*x^17 + 87*x^16 + 118*x^15 - 1246*x^14 - 265*x^13 + 1613*x^12 + 396*x^11 + 2296*x^10 + 896*x^9 - 3160*x^8 - 662*x^7 + 1270*x^6 + 167*x^5 - 243*x^4 - 20*x^3 + 24*x^2 + (9*x^16 + 352*x^14 - 1063*x^12 - 356*x^10 + 1810*x^8 - 934*x^6 + 203*x^4 - 22*x^2 + 1)*sqrt(-3*x^2 - 2*x + 1) + x - 1)*sqrt(-3*x^2 + 2*x + 1) - (9*x^17 - 87*x^16 + 118*x^15 + 1246*x^14 - 265*x^13 - 1613*x^12 + 396*x^11 - 2296*x^10 + 896*x^9 + 3160*x^8 - 662*x^7 -

KeyboardInterrupt: ECL says: Console interrupt.

In [ ]:
x,y,z,a = var('x,y,z,a')
t2 = t.subs(x==a*z)
t3 = t2.subs(y==a/z)

z_0 = 0
z_1 = (-a+1+sqrt(-3*a**2 -2*a+1))/(2*a)
z_2 = (-a+1-sqrt(-3*a**2 -2*a+1))/(2*a)
z_3 = (a+1+sqrt(-3*a**2 +2*a+1))/(2*a)
z_4 = (a+1-sqrt(-3*a**2 +2*a+1))/(2*a)
z_5 = 1/a
z_6 = a

# denominator_factor = r*(z-z_1)*(z-z_2)*r*(z-z_3)*(z-z_4)*(r*z-1)**4 * (r-z)**4


# term1 = (t3.numerator()/((z*denominator_factor).derivative(z))).subs(z==z_1)
# term2 = (t3.numerator()/((z*denominator_factor).derivative(z))).subs(z==z_2)
# term3 = (t3.numerator()/((z*denominator_factor).derivative(z))).subs(z==z_3)
# term4 = (t3.numerator()/((z*denominator_factor).derivative(z))).subs(z==z_4)


# assert denominator_factor == t3.denominator()

# denominator_factor2 = r*(z-z_1)*r*(z-z_3)*(z-z_4)*(r*z-1)**4 *(r-z)**4
# z_2_term = (t3.numerator()/(z*denominator_factor2))
# z_2_term = (t3.numerator()/(z*denominator_factor2)).subs(z==z_2)

# z_2_term_2 = (t3.numerator()/((z*denominator_factor).derivative(z))).subs(z==z_2)
# assert z_2_term == z_2_term_2

# denominator_factor4 = r*(z-z_1)*(z-z_2)*r*(z-z_3)*(r*z-1)**4 *(r-z)**4
# z_4_term = (t3.numerator()/(z*denominator_factor4)).subs(z==z_4)

# z_4_term_2 = (t3.numerator()/((z*denominator_factor).derivative(z))).subs(z==z_4)
# assert z_4_term == z_4_term_2


# denominator_factor6 = r*(z-z_1)*(z-z_2)*r*(z-z_3)*(z-z_4)*(r*z-1)**4
# z_6_term = (((t3.numerator()/(z*denominator_factor6)).derivative(z).derivative(z).derivative(z))/6).subs(z==z_6)
# assert z_6_term == (t3/z).residue(z == r)


# print((z_2_term + z_4_term + z_6_term).simplify_full())
# print(latex((z_2_term + z_4_term + z_6_term).simplify_full()))

# print((t3/z).numerator().subs(z==0).simplify_full())
# print((t3/z).denominator().subs(z==0).simplify_full())

print(factor(t3.numerator()))

# print((t3/z).residue(z == 0).simplify_full())
# print((t3/z).residue(z == z_1).simplify_full())
# print((t3/z).residue(z == z_2).simplify_full())
# print((t3/z).residue(z == z_3).simplify_full())
# print((t3/z).residue(z == z_4).simplify_full())
# print((t3/z).residue(z == z_5).simplify_full())
# print((t3/z).residue(z == z_6).simplify_full())